/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package silver.ore.app

import org.jline.terminal.Attributes
import org.jline.terminal.Terminal
import org.jline.terminal.TerminalBuilder
import org.jline.utils.InfoCmp
import silver.ore.app.utils.GlobalCubeCoordinates

fun main() {
//    val worlds = Array(1) { i -> World() }
//    println(worlds[0].getCube(Random.nextInt(0,255), Random.nextInt(0,255), 128).display())
    val builder: TerminalBuilder = TerminalBuilder.builder()
    builder.system(true)
    val terminal: Terminal = builder.build()
    println(terminal.name + ": " + terminal.type)
    terminal.echo(false)
    val attributes = terminal.attributes
    attributes.setLocalFlag(Attributes.LocalFlag.ICANON, false)
    terminal.attributes = attributes;
    val reader = terminal.reader()

    if (terminal.type == "dumb-color" || terminal.type == "dumb") {
        println("Your terminal is ${terminal.type}. Continue to work? (y/n)")
        var integer: Int
        var char: Char
        do {
            integer = reader.read()
            char = integer.toChar().lowercaseChar()
        } while(integer >= 0 && char != 'y' && char != 'n')

        if (integer < 0 || char == 'n') {
            return
        }
    }

    val world = World(WorldConfig(generatorName = "i1"))
    var x = 128
    var y = 128
    var z = 128
    do {
        println("X: $x, Y: $y, Z: $z")
        println("Chunk: ${world.getChunkByCoordinates(GlobalCubeCoordinates(x, y, z))} / Chunks loaded: ${world.chunksLoaded()} / Cubes loaded: ${world.cubesLoaded()}")
        val cube = world.getCube(GlobalCubeCoordinates(x, y, z))
        println(cube.fullDisplay())
        val item = cube.getItem()
        if (item != null) {
            println("Item: ${item.getName()}")
        } else {
            println("No items")
        }
        for (i in -16..16) {
            var row: String = ""
            for (j in -24..24) {
                if (i != 0 || j != 0) {
                    row += world.getCube(GlobalCubeCoordinates(x + j, y + i, z)).display()
                } else {
                    row += "x"
                }
            }
            println(row)
        }
        val integer = reader.read()
        val char = integer.toChar()
        when (char) {
            'w' -> {
                y--
            }
            's' -> {
                y++
            }
            'a' -> {
                x--
            }
            'd' -> {
                x++
            }
            'e' -> {
                z--
            }
            'r' -> {
                z++
            }
        }
        terminal.puts(InfoCmp.Capability.clear_screen);
        terminal.flush();
    } while (char != 'q' && integer != -1)
}
