/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("silver.ore.kotlin-application-conventions")
}

application {
    // Define the main class for the application.
    mainClass.set("silver.ore.terminal.AppKt")
}

dependencies {
    implementation("com.github.doyaaaaaken:kotlin-csv-jvm:1.2.0")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.jline:jline:3.21.0")
    implementation(project(":app"))
}

